# Copyright (C) Microsoft Corporation. All rights reserved.
# Licensed under the MIT license. See LICENSE.txt in the project root for license information.

configuration:
  - Debug
  - Release

image: Visual Studio 2017

environment:
  RunCodeAnalysis: true
  TreatWarningsAsErrors: true

branches:
  only:
    - master
    - develop

skip_tags: true

notifications:
  - provider: GitHubPullRequest
    on_build_success: true
    on_build_failure: true

cache:
  - packages -> **\packages.config

install:
  - ps: |
      $ErrorActionPreference = 'Stop'
      Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
      Install-Module -Name platyPS -Repository PSGallery -SkipPublisherCheck -Force

before_build:
  - nuget restore
  - ps: New-ExternalHelp -Path $env:APPVEYOR_BUILD_FOLDER\docs\VSSetup -OutputPath $env:APPVEYOR_BUILD_FOLDER\src\VSSetup.PowerShell\bin\$env:CONFIGURATION -Force

build:
  parallel: true

after_build:
  - 7z a bin\%CONFIGURATION%\VSSetup.zip %APPVEYOR_BUILD_FOLDER%\LICENSE.txt
  - 7z a bin\%CONFIGURATION%\VSSetup.zip %APPVEYOR_BUILD_FOLDER%\src\VSSetup.PowerShell\bin\%CONFIGURATION%\*.dll
  - 7z a bin\%CONFIGURATION%\VSSetup.zip %APPVEYOR_BUILD_FOLDER%\src\VSSetup.PowerShell\bin\%CONFIGURATION%\*.dll-Help.xml
  - 7z a bin\%CONFIGURATION%\VSSetup.zip %APPVEYOR_BUILD_FOLDER%\src\VSSetup.PowerShell\bin\%CONFIGURATION%\about_*.help.txt
  - 7z a bin\%CONFIGURATION%\VSSetup.zip %APPVEYOR_BUILD_FOLDER%\src\VSSetup.PowerShell\bin\%CONFIGURATION%\VSSetup.*
  - nuget pack -BasePath "%APPVEYOR_BUILD_FOLDER%" -OutputDirectory "bin\%CONFIGURATION%" -Version "%GitBuildVersionSimple%" -Properties "Configuration=%CONFIGURATION%;CommitId=%APPVEYOR_REPO_COMMIT%" pkg\VSSetup\VSSetup.nuspec

test_script:
  - tools\test.cmd -v

artifacts:
  - path: bin\$(configuration)\VSSetup.zip
    name: VSSetup

  - path: bin\$(configuration)\*.nupkg
    name: package

deploy:
  - provider: GitHub
    description: 'Prerelease of version $(appveyor_build_version)'
    prerelease: true
    auth_token:
      secure: OQYrPN9oRtZHmy6BthAD7WrNdNMIhjOj5J+1YO96vnYnAhQ3ZRTGg0naaAlUsvpW
    artifact: VSSetup
    on:
      branch: develop
      configuration: Release

  - provider: NuGet
    server: https://powershellgallery.com
    api_key:
      secure: zlSsf1CjcEIqOM58eGv9sOJmGL24l9sFfE+GxftIiD3bJwJKNnlwbfe1/H81TQQD
    artifact: package
    skip_symbols: true
    on:
      branch: develop
      configuration: Release

  - provider: NuGet
    server: https://nuget.smbsrc.net/
    api_key:
      secure: d8ZqLghGiOFGr7Bu1x69hHKaopNtHRCmex72n6n7Ul80enJWM65tw9c1wlnXw4yP
    artifact: /.*\.symbols\.nupkg/
    on:
      branch: develop
      configuration: Release

# vim: set ai et st=2 sts=2 sw=2:
